apiVersion: v1
kind: Service
metadata:
  name: service-backend-iot
  namespace: development
spec:
  type: LoadBalancer
  selector:
    app: backend-iot
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080
